//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceCompare.Backend.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chain
    {
        public string ChainId { get; set; }
        public string ChainName { get; set; }
        public string ChainWebSiteLink { get; set; }
        public string ChainUserName { get; set; }
        public string ChainPassword { get; set; }
    }
}
