//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceCompare.Backend.Data.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PriceCompareDBEntities : DbContext
    {
        public PriceCompareDBEntities()
            : base("name=PriceCompareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chain> Chains { get; set; }
        public virtual DbSet<ProductPriceByChain> ProductPriceByChains { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    
        public virtual int DeleteProductPriceByChainsTableRows()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProductPriceByChainsTableRows");
        }
    
        public virtual int DeleteProductsTableRows()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProductsTableRows");
        }
    }
}
